spring.application.name=PAYMENT_BACKEND
server.port=8080

firebase.config-path=classpath:serviceAccountKey.json

momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz

momo.redirect-url=https://momo.vn
momo.ipn-url=https://5fcb-2405-4802-1cd3-b2e0-60bf-a2d7-6953-30ed.ngrok-free.app/api/payment/momo-ipn