spring.application.name=PAYMENT_BACKEND
server.port=8080

firebase.config-path=classpath:serviceAccountKey.json

momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.partner-code=MOMOJH1T20260418_TEST
momo.access-key=p35ezPtIupH2eiHu
momo.secret-key=UMNByLx4TKWVteSGhwA24bEPnKBVQZWK

momo.redirect-url=https://momo.vn
<<<<<<< Updated upstream
momo.ipn-url=https://e4b5-2405-4802-47e-90f0-c528-fe64-1dc2-dfe9.ngrok-free.app/api/payment/momo-ipn
=======
#momo.ipn-url=${NGROK_IPN_URL}
momo.ipn-url=https://latrine-dotted-repugnant.ngrok-free.dev/api/payment/momo-ipn
>>>>>>> Stashed changes
